### ISSUE TITLE
FlowAuth admin can't reset existing user's password

### ISSUE THREAD

**Issue by jch1g10** [Flowminder/FlowKit#1635]
**Describe the bug**

If I log into FlowAuth as an admin user, edit an existing user, and try to reset the user's password, I get re-directed to the login screen and the changes don't take effect (no error message is shown).

**To Reproduce**

1. Spin up FlowAuth in demo mode, and log in as 'TEST_ADMIN'.
2. Select the 'Users' tab, and edit 'TEST_USER'.
3. In the password box, click the password reset icon.
4. Select 'Save'.
5. The login screen appears.
6. Try logging in as 'TEST_USER' - the password has not changed.

**Expected behaviour**

Admin users should be able to reset other users' passwords through the FlowAuth UI.

**Comment by greenape** [comment]
Presumably there's an error happening on the backend - traceback from the flask app?

**Comment by jch1g10** [comment]
```
[2019-12-02 11:43:49,593] ERROR in app: Exception on /admin/users/1 [PATCH]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_principal.py", line 199, in _decorated
    rv = f(*args, **kw)
  File "/usr/local/lib/python3.6/site-packages/flowauth/admin.py", line 714, in edit_user
    if len(edits["password"]) > 0:
TypeError: object of type 'bool' has no len()
```

**Comment by jch1g10** [comment]
Looks like https://github.com/Flowminder/FlowKit/blob/d3ef12db26ffeaaeaffa304091ad3b25145a8f18/flowauth/frontend/src/UserAdminDetails.jsx#L146 is causing the problem
